### ISSUE TITLE
Sorry, Who could tell me to  set up the loss type, when I use the L1 loss or L2 loss?  

### ISSUE THREAD

**Issue by 2269866108** [NVlabs/PL4NN#2]
layer {
  name: "loss"
  type: "L2"
  bottom: "conv16"
  bottom: "label"
  top: "loss"
}
Where can  I get the whole ‘caffe’ package for the L1 loss and L2 loss?

**Comment by hangzhaomit** [comment]
@2269866108 
Here is an example usage of the python layer.

```
layer {
    name: "lossL1"
    type: "Python"
    bottom: "conv3"
    bottom: "label"
    top: "lossL1"
    python_param {
        module: "loss"
        layer: "L1"
    }
    loss_weight: 1
}
```
