### ISSUE TITLE
eval function cause error

### ISSUE THREAD

**Issue by elysion122** [NVlabs/PL4NN#3]
I implemented loss.py in caffe，however it didn‘t work ，can you help me solve the problem? Thank you very much.
···
Traceback (most recent call last):
  File "/home/mitc/video-caffe-refactor/python/loss.py", line 303, in setup
    params = eval(self.param_str)
  File "<string>", line 0
    
    ^
···
I tried to find a solution on internet, It seemed that empty  eval function caused the problem.
how can I fix it？？

**Comment by hangzhaomit** [comment]
@elysion122 
Hi, you need to input "python_param" in your loss in prototxt file. Here is an example:
```
layer {
    name: "lossL1"
    type: "Python"
    bottom: "conv3"
    bottom: "label"
    top: "lossL1"
    python_param {
        module: "loss"
        layer: "L1"
    }
    loss_weight: 1
}
```

**Comment by elysion122** [comment]
Thank you so much!

2017-12-07 10:38 GMT+08:00 Hang Zhao <notifications@github.com>:
