### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by rgsl888** [NVlabs/PL4NN#5]
Hi All,
              I am trying use MSSSIM-L2 for one of my projects and I am getting memory error due ti huge size of the array. Was it an issue that was seen by you while testing this code. My image size is 400x275.

**Comment by hangzhaomit** [comment]
It is possible that with a large image size, memory overflows. In our experiments, we always used patches with size <100x100. So please try to crop your images into patches. By the way, odd patch side length is preferred.

**Comment by rgsl888** [comment]
Can it take images with different height and width, such as 400 x 275, because only image width is being considered ans nothing else

**Comment by hangzhaomit** [comment]
In the training, with our implementation, input must be patches.
At test time, you can feed in images with arbitrary size, because loss layer is not used.

**Comment by rgsl888** [comment]
What if I provide input as an image with 401 x 277? As per my observation, it gives error.

**Comment by hangzhaomit** [comment]
Is it training time? Please use patches instead, try 31x31.

**Comment by rgsl888** [comment]
In my case, whole image has an entity and I can't send just patch of it as an input to the whole network.
If I can send patches to the loss function and get back loss values for whole image would be more useful in my case.

Is this scenario possible in caffe ?

**Comment by hangzhaomit** [comment]
I do not think so...

**Comment by rgsl888** [comment]
Thank you for useful information, have nice day
